import { useState } from 'react';
import Modal from './Modal.jsx';
import { DEFAULT_BINDINGS, validateBinding, keyLabel } from '../game/controls.js';
export default function Settings({settings:s,onChange,onResetSave,onClose}) {
  const [tab,setTab]=useState('Gameplay'),[reset,setReset]=useState(false),[message,setMessage]=useState(''),[capture,setCapture]=useState(null);
  const slider=(key,label,min,max,step=.05)=><label className="setting-row" key={key}><span>{label}<small>{Math.round(s[key]*100)}%</small></span><input aria-label={label} type="range" min={min} max={max} step={step} value={s[key]} onChange={e=>onChange({[key]:Number(e.target.value)})}/></label>;
  const toggle=(key,label)=><label className="setting-row" key={key}><span>{label}</span><input type="checkbox" checked={s[key]} onChange={e=>onChange({[key]:e.target.checked})}/></label>;
  return <Modal title="Settings" onClose={onClose}><div className="tabs">{['Gameplay','Audio','Display','Controls','Accessibility'].map(name=><button key={name} className={`chip ${tab===name?'on':''}`} onClick={()=>{setTab(name);setCapture(null);}}>{name}</button>)}</div>
    {tab==='Gameplay'&&<><label className="setting-row"><span>Touch controls</span><select className="select" value={s.touch} onChange={e=>onChange({touch:e.target.value})}>{['auto','on','off'].map(v=><option key={v}>{v}</option>)}</select></label><p className="muted">Explore at your own pace. Progress saves automatically, and discovery streaks have no timer.</p>{!reset?<button className="btn danger small" onClick={()=>setReset(true)}>Reset save</button>:<div className="confirmation"><h3>Reset your adventure?</h3><p>This permanently erases your progress in this browser.</p><div className="row"><button className="btn ghost" data-autofocus onClick={()=>setReset(false)}>Cancel</button><button className="btn danger" onClick={()=>{onResetSave();setReset(false);}}>Reset Progress</button></div></div>}</>}
    {tab==='Audio'&&<>{slider('master','Master Volume',0,1)}{slider('music','Music Volume',0,1)}{slider('sfx','Sound Volume',0,1)}<button className="btn ghost small" onClick={()=>onChange({master:s.master?0:1})}>{s.master?'Mute all audio':'Enable audio'}</button></>}
    {tab==='Display'&&<>{slider('uiScale','UI Scale',.8,1.4)}{slider('textScale','Text Size',1,1.5)}<button className="btn ghost" onClick={async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();setMessage('Display updated.');}catch{setMessage('Fullscreen is unavailable in this browser.');}}}>Toggle Fullscreen</button></>}
    {tab==='Accessibility'&&<>{toggle('highContrast','High Contrast')}{toggle('reducedMotion','Reduced Motion')}{toggle('screenShake','Screen Shake')}{slider('animationIntensity','Animation Intensity',0,1)}{slider('textScale','Text Size',1,1.5)}<p className="muted">Rarity always includes a symbol and text. Menus work with Tab, Enter, and Escape.</p></>}
    {tab==='Controls'&&<><p className="muted">Select an action, then press a letter or number. Arrow keys always move; Escape always closes menus.</p><div className="binding-grid">{Object.entries(s.bindings).map(([action,code])=><div className="setting-row" key={action}><span>{action.replace(/([0-9])/g,' $1')}</span><button className="chip" onClick={()=>setCapture(action)} onKeyDown={e=>{if(capture!==action)return;e.preventDefault();e.stopPropagation();if(e.code==='Escape'){setCapture(null);return;}const result=validateBinding(s.bindings,action,e.code);if(result.ok){onChange({bindings:{...s.bindings,[action]:e.code}});setCapture(null);setMessage('Controls updated.');}else setMessage(result.reason);}}>{capture===action?'Press a key…':keyLabel(code)}</button></div>)}</div><button className="btn ghost small" onClick={()=>{onChange({bindings:DEFAULT_BINDINGS});setCapture(null);}}>Restore default controls</button></>}
    <p role="status" className="muted">{message}</p>
  </Modal>;
}
