import assert from 'node:assert/strict';
import { browserSession } from './browser-session.mjs';
const b=await browserSession();
const wait=()=>new Promise(r=>setTimeout(r,350));
const key=async(code,key)=>{await b.send('Input.dispatchKeyEvent',{type:'keyDown',code,key});await b.send('Input.dispatchKeyEvent',{type:'keyUp',code,key});await wait();};
try {
  await b.send('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});
  await b.send('Page.navigate',{url:'http://127.0.0.1:5173/?debug'});await new Promise(r=>setTimeout(r,1800));
  await b.evaluate(`localStorage.clear();location.reload()`);await new Promise(r=>setTimeout(r,800));
  await b.clickText('New Game');await wait();
  console.log('Gameplay',await b.evaluate(`({text:document.body.innerText,canvas:[document.querySelector('canvas').width,document.querySelector('canvas').height]})`));
  assert.equal(await b.evaluate(`window.__moneyHunter.rt.mode`),'explore');
  await b.screenshot('.qa/gameplay.png');
  await b.evaluate(`window.__moneyHunter.discover('php1')`);await wait();
  assert.equal(await b.evaluate(`window.__moneyHunter.rt.mode`),'explore');
  assert.ok(await b.evaluate(`document.querySelector('.reward-card')?.textContent.includes('Explorer XP')`));
  await b.screenshot('.qa/discovery.png');
  await key('KeyC','c');assert.ok(await b.evaluate(`!!document.querySelector('.album')`));
  await b.screenshot('.qa/encyclopedia.png');
  await b.clickText('Collections');await b.screenshot('.qa/collections.png');await key('Escape','Escape');
  await key('Escape','Escape');assert.match(await b.evaluate('document.activeElement.textContent'),/Resume/);
  await b.clickText('Explorer Shop');await b.clickText('Upgrades');await b.screenshot('.qa/shop.png');
  await b.evaluate(`window.__moneyHunter.s.progression.coins=500;window.__moneyHunter.emit('change')`);await wait();
  await b.clickText('View purchase');await b.clickText('Buy · 350');await wait();
  assert.equal(await b.evaluate(`window.__moneyHunter.s.progression.coins`),150);
  assert.equal(await b.evaluate(`window.__moneyHunter.s.progression.purchases.rare_scanner`),true);
  await key('Escape','Escape');await b.clickText('Skills');await b.screenshot('.qa/skills.png');await key('Escape','Escape');
  for(const menu of ['Achievements','Progress','People & Requests','Settings']) {await b.clickText(menu);await wait();assert.ok(await b.evaluate(`!!document.querySelector('[role=dialog]')`));await key('Escape','Escape');}
  await b.clickText('Resume Adventure');await b.evaluate(`window.__moneyHunter.save()`);
  await key('Digit4','4');assert.match(await b.evaluate(`document.querySelector('.tabs .on').textContent`),/Maps/);await key('Escape','Escape');
  await b.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await wait();
  await b.screenshot('.qa/mobile-gameplay.png');
  console.log('Mobile canvas',await b.evaluate(`({w:document.querySelector('canvas').width,h:document.querySelector('canvas').height,scroll:document.documentElement.scrollWidth,width:innerWidth})`));
  await key('KeyC','c');await b.screenshot('.qa/mobile-encyclopedia.png');
  assert.ok(await b.evaluate(`document.querySelector('.album').getBoundingClientRect().right<=innerWidth`));
  await key('Escape','Escape');await key('Escape','Escape');await b.clickText('Return to Main Menu');await b.clickText('Continue adventure');
  assert.match(await b.evaluate('document.body.innerText'),/Your adventure awaits/);
  await b.clickText('Continue Adventure');await wait();
  assert.equal(await b.evaluate(`window.__moneyHunter.s.progression.purchases.rare_scanner`),true);
  await b.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});
  await b.evaluate(`window.__moneyHunter.setSettings({...window.__moneyHunter.settings,touch:'on'})`);
  await key('Escape','Escape');await b.clickText('Settings');
  await b.evaluate(`(()=>{const s=document.querySelector('select');s.value='on';s.dispatchEvent(new Event('change',{bubbles:true}));})()`);await wait();
  await b.clickText('Accessibility');
  await b.evaluate(`(()=>{const labels=[...document.querySelectorAll('label')];labels.find(l=>l.textContent.includes('Reduced Motion')).querySelector('input').click();labels.find(l=>l.textContent.includes('High Contrast')).querySelector('input').click();})()`);await wait();
  assert.equal(await b.evaluate(`document.documentElement.dataset.motion`),'reduced');
  assert.equal(await b.evaluate(`window.__moneyHunter.settings.reducedMotion`),true);
  await b.clickText('Controls');
  await b.evaluate(`(()=>{const row=[...document.querySelectorAll('.setting-row')].find(r=>r.querySelector('span')?.textContent==='inventory');row.querySelector('button').click();row.querySelector('button').focus();})()`);
  await key('KeyV','v');
  assert.equal(await b.evaluate(`window.__moneyHunter.settings.bindings.inventory`),'KeyV');
  await key('Escape','Escape');await b.clickText('Resume Adventure');await wait();
  assert.ok(await b.evaluate(`!!document.querySelector('.touch .pad')`));
  await b.screenshot('.qa/mobile-touch.png');
  await key('KeyV','v');assert.match(await b.evaluate('document.body.innerText'),/Backpack/);await key('Escape','Escape');
  await b.send('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});
  // Use a single actual Legendary entry for the major celebration.
  await b.evaluate(`import('/src/data/currencies.js').then(({CURRENCIES})=>window.__moneyHunter.discover(CURRENCIES.find(c=>c.rarity==='Legendary').id))`);await wait();
  assert.match(await b.evaluate('document.body.innerText'),/Legendary Discovery/);
  await b.screenshot('.qa/legendary.png');await key('Escape','Escape');
  await b.evaluate(`import('/src/data/currencies.js').then(({CURRENCIES})=>{for(const c of CURRENCIES)window.__moneyHunter.discover(c.id,{silent:true});})`);await wait();
  assert.match(await b.evaluate('document.body.innerText'),/MONEY ENCYCLOPEDIA COMPLETE/);
  assert.equal(await b.evaluate(`getComputedStyle(document.querySelector('.adventure-hud')).visibility`),'hidden');
  await b.screenshot('.qa/completion.png');await b.clickText('Continue exploring');await wait();
  assert.equal(await b.evaluate(`window.__moneyHunter.rt.paused`),false);
  const currencyBalance=await b.evaluate(`window.__moneyHunter.s.progression.coins`);
  await b.evaluate(`window.__moneyHunter.save();location.reload()`);await new Promise(r=>setTimeout(r,900));
  await b.clickText('Continue adventure');await b.clickText('Continue Adventure');await wait();
  assert.equal(await b.evaluate(`window.__moneyHunter.s.progression.coins`),currencyBalance);
  // Corrupt storage recovery must never clear original bytes or enable Continue.
  await key('Escape','Escape');await b.clickText('Return to Main Menu');await wait();
  await b.evaluate(`localStorage.setItem('moneyhunter.save.v1','{broken');location.reload()`);await new Promise(r=>setTimeout(r,900));
  assert.match(await b.evaluate('document.body.innerText'),/Unable to load save data/);
  assert.equal(await b.evaluate(`localStorage.getItem('moneyhunter.save.v1')`),'{broken');
  await b.clickText('Try again');assert.equal(await b.evaluate(`localStorage.getItem('moneyhunter.save.v1')`),'{broken');
  assert.equal(b.errors.length,0,JSON.stringify(b.errors));
  console.log('PASS: browser gameplay, discovery, encyclopedia, collections, shop purchase, menu focus, skills, mobile touch, remapping, reduced motion, high contrast, legendary/completion, save/continue and corrupt-save recovery');
} finally {b.close();}
